((nil . ((cider-clojure-cli-global-options     . "-A:dev:test:build")
         (cider-preferred-build-tool           . clojure-cli)
         (cider-redirect-server-output-to-repl . t)
         (cider-repl-display-help-banner       . nil)
         (clojure-toplevel-inside-comment-form . t)))
 (clojure-mode . ((eval . (define-clojure-indent
                            (as-> 1)
                            (match 1)
                            (nippy/extend-freeze 2)
                            (nippy/extend-thaw 1))))))
